# This file contains values from Cookiecutter

default_context:
  project_name: "filter-regions"
  project_description: "Filter genomic regions by score and proximity"
  organization: "Altius Institute for Biosciences"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "filter-regions"
  email: "alexpreynolds@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
